#!/usr/bin/env python

# -*- coding: utf-8 -*-

import sys
import re

if len(sys.argv) != 2:
  sys.stderr.write('%s [LC section name (e.g. LC_TIME)]\n' % sys.argv[0])
  sys.exit(1)

lc_section = sys.argv[1]
possible_lc_sections = ['LC_CTYPE', 'LC_NUMERIC', 'LC_TIME', 'LC_COLLATE', 'LC_MONETARY', 'LC_MESSAGES', 'LC_PAPER',
                        'LC_NAME', 'LC_ADDRESS', 'LC_TELEPHONE', 'LC_MEASUREMENT', 'LC_IDENTIFICATION', 'LC_ALL']

if lc_section not in possible_lc_sections:
  sys.stderr.write('Non existing LC section %s\n' % lc_section)
  sys.exit(1)

lc_section_pattern = r'\n{0}(.*?)END\s+{0}'.format(lc_section)

lines = ''
for line in sys.stdin:
  lines += line

match = re.search(lc_section_pattern, lines, re.DOTALL)

sys.stdout.write('comment_char %\n')
sys.stdout.write('escape_char  /\n')

if match:
  sys.stdout.write(match.group(1).lstrip('\n'))

sys.exit(0)
