#!/usr/bin/env bash
#
# set -x;
set -e;
set -o pipefail;
#
thisFile="$(readlink -f ${0})";
thisFilePath="$(dirname ${thisFile})";

cd "${thisFilePath}/../../";

if [ -z "${1}" ]; then
  echo "Use the script as described below:";
  echo "${0} [ locale (e.g. nl_NL) ]";
  exit 1;
fi

locale="${1}"

# Encode
bin/locale-decode-category < \
  glibc_locale_tools/test/data/${locale}.LC_TIME.expected > \
  glibc_locale_tools/test/data/${locale}.LC_TIME.decoded;

diff -u glibc_locale_tools/test/data/${locale}.LC_TIME.expected-decoded \
  glibc_locale_tools/test/data/${locale}.LC_TIME.decoded;

# Encode
bin/locale-encode-category < \
  glibc_locale_tools/test/data/${locale}.LC_TIME.decoded > \
  glibc_locale_tools/test/data/${locale}.LC_TIME.encoded;

diff -u glibc_locale_tools/test/data/${locale}.LC_TIME.expected \
  glibc_locale_tools/test/data/${locale}.LC_TIME.encoded;
