#!/usr/bin/env bash
#
# set -x;
set -e;
set -o pipefail;
#
thisFile="$(readlink -f ${0})";
thisFilePath="$(dirname ${thisFile})";

locale="${1}"

../../bin/locale-decode < data/${locale} > data/${locale}.decoded;
../../bin/locale-encode < data/${locale}.decoded > data/${locale}.encoded;

diff -u data/${locale} data/${locale}.encoded;
